### PR TITLE
Fixed reloading app config

### PR DESCRIPTION
**Pull request by zuker**
Fix for #2

### CODE REVIEW

**Comment by tjwebb** [comment]
I decided that watching config changes wouldn't be a good idea. If you add/remove a trailpack that is loaded in `main.packs`, weird things will happen. What if you change `main.paths`? I think config changes should require shutting down the app.

**Comment by zuker** [comment]
Livereload-incompatible pieces of config could be excluded from watcher list. Is it acceptable?

**Comment by tjwebb** [comment]
I think the docs are also wrong on this, since they mention `config/`. 

> Livereload-incompatible pieces of config could be excluded from watcher list. Is it acceptable?
>  Show all checks

Possibly, but I still am not convinced that this is a good idea.

**Comment by zuker** [comment]
Ok, I see, anyway I don't think that this is a critical issue.

**Pull request closed without merging**
